version: '3'

services:
  db_auth:
    image: postgres
    container_name: db_auth
    restart: always
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
